[build]
  command = "npm run build"
  publish = "build"
  functions = "server/functions"

[dev]
  command = "npm run start"
  port = 8888
  targetPort = 3000
  publish = "build"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200